### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by tonga56** [zbnio/zbn#2]
第一次登陆的时候就报错：
            * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
[2020-11-16 11:17:02,411] ERROR in app: Exception on /api/v1/login [POST]
Traceback (most recent call last):
  File "D:\python\python37\lib\site-packages\flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "D:\python\python37\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by sanjinhub** [comment]
1.代码有改动？
2.是否进入项目当前目录运行？

**Comment by tonga56** [comment]
代码没动，在web界面登陆，这边报的错
