### ISSUE TITLE
剧本执行报错。

### ISSUE THREAD

**Issue by 3199246101** [zbnio/zbn#7]
生成了一个端口扫描的剧本执行没反应？后台看有报错提示
* Welcome to ZBN SOAR service
===========================
* Web : https://zbn.io
* Github : https://github.com/zbnio/zbn
===========================
* Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\gevent\pywsgi.py", line 970, in handle_one_response    self.run_application()
  File "C:\Program Files\Python37\lib\site-packages\geventwebsocket\handler.py", line 75, in run_application self.run_websocket()
  File "C:\Program Files\Python37\lib\site-packages\geventwebsocket\handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: [])) File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2464, in__call__  return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python37\lib\site-packages\flask_sockets.py", line 45,in __call__handler(environment, **values)
  File "D:\software\ZBN\app\handler\workflow\view.py", line 113, in echo_socket   run_exec(socket=socket, uuid=uuid)
  File "core.py", line 138, in core.run_exec
  File "core.py", line 69, in core.get_app_data
  File "core.py", line 50, in core.execute
UnboundLocalError: local variable 'import_path' referenced before assignment2020-11-16T05:01:05Z {'REMOTE_ADDR': '192.168.10.200', 'REMOTE_PORT': '52564', 'HTTP_HOST': '192.168.10.222:8888', (hidden keys: 32)} failed with UnboundLocalError

**Comment by sanjinhub** [comment]
请更新到 v0.1.1， 另外本机要安装 nmap 工具

**Comment by 3199246101** [comment]
> 请更新到 v0.1.1， 另外本机要安装 nmap 工具

更新到0.1.1版本已经解决了，非常感谢！
